# Generated by Django 2.2.4 on 2019-09-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('notes', models.TextField(max_length=2048, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.course_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FirstCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Course')),
                ('contentType', models.CharField(choices=[('T', 'Terra'), ('M', 'Mare')], max_length=1)),
                ('cookingType', models.CharField(choices=[('C', 'Caldo'), ('F', 'Freddo')], max_length=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.course',),
        ),
        migrations.CreateModel(
            name='SecondCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Course')),
                ('contentType', models.CharField(choices=[('T', 'Terra'), ('I', 'Insalatona')], max_length=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.course',),
        ),
        migrations.CreateModel(
            name='SideCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Course')),
                ('cookingType', models.CharField(choices=[('V', 'Vapore'), ('F', 'Forno'), ('N', 'Non definito')], max_length=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.course',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumeDate', models.DateField()),
                ('sendDate', models.DateTimeField()),
                ('courses', models.ManyToManyField(through='app.ContentMenu', to='app.Course')),
            ],
        ),
        migrations.AddField(
            model_name='contentmenu',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
        migrations.AddField(
            model_name='contentmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Menu'),
        ),
    ]
