# Generated by Django 2.2.5 on 2019-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstcourse',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='firstcourse',
            old_name='cookingType',
            new_name='cooking_type',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='consumeDate',
            new_name='consume_date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='sendDate',
            new_name='send_date',
        ),
        migrations.RenameField(
            model_name='secondcourse',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='sidecourse',
            old_name='cookingType',
            new_name='cooking_type',
        ),
    ]
