# Generated by Django 2.2.5 on 2019-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190903_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='firstcourse',
            name='cookingType',
            field=models.CharField(choices=[('C', 'Caldo'), ('F', 'Freddo')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='firstcourse',
            name='contentType',
            field=models.CharField(choices=[('T', 'Terra'), ('M', 'Mare')], max_length=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='secondcourse',
            name='contentType',
            field=models.CharField(choices=[('T', 'Terra'), ('I', 'Insalatona')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sidecourse',
            name='cookingType',
            field=models.CharField(choices=[('V', 'Vapore'), ('F', 'Forno'), ('N', 'Non definito')], max_length=1),
        ),
    ]
