# Generated by Django 2.2.5 on 2019-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190903_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcourse',
            name='dishType',
            field=models.CharField(choices=[('0', 'Caldo'), ('1', 'Freddo')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
