# Generated by Django 2.2.5 on 2019-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190904_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='consumeDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sendDate',
            field=models.DateTimeField(),
        ),
    ]
